USE CovidHurtowniaDanych
GO

DROP TABLE IF EXISTS [dbo].[stage_tempo_fact]

CREATE TABLE [dbo].[stage_tempo_fact]
(
	[FAKT_ID] [int] IDENTITY(1,1) NOT NULL,
	[CZAS] nvarchar(50) NULL,
	[GEOGRAFIA] nvarchar(50) NULL,
	[LICZBA_ZAKAZENI_OGOLEM] [int] NULL,
	[LICZBA_ZGONOW_OGOLEM] [int] NULL,
	[LICZBA_WYLECZONYCH_OGOLEM] [int] NULL,
	[LICZBA_NOWYCH_ZAKAZEN_DZIS] [int] NULL,
	[LICZBA_NOWYCH_ZGONOW_DZIS] [int] NULL,
	[LICZBA_NOWYCH_WYLECZONYCH_DZIS] [int] NULL,
	[LICZBA_ZAKAZONYCH_NA_DZIS] [int] NULL,
	[DYNAMIKA_ZAKAZEN] [float] NULL,
	[NUMER_KOLEJNY_DNIA] [int] NULL
)