USE [master];
GO

IF EXISTS (SELECT [name]
FROM [master].[sys].[databases]
WHERE [name] = 'CovidHurtowniaDanych')
    DROP DATABASE [CovidHurtowniaDanych];
GO

CREATE DATABASE [CovidHurtowniaDanych];
GO

USE [CovidHurtowniaDanych];
GO

-- ****************************************
-- Tabele
-- ****************************************

CREATE TABLE [dbo].[TEMPO_WIRUSA_SUM]
(
	[FAKT_ID] [int] IDENTITY(1,1) NOT NULL,
	[CZAS_ID] [int] NOT NULL,
	[GEOGRAFIA_ID] [int] NOT NULL,
	[LICZBA_ZAKAZENI_OGOLEM] [int] NOT NULL,
	[LICZBA_ZGONOW_OGOLEM] [int] NOT NULL,
	[LICZBA_WYLECZONYCH_OGOLEM] [int] NOT NULL,
	[LICZBA_NOWYCH_ZAKAZEN_DZIS] [int] NOT NULL,
	[LICZBA_ZAKAZONYCH_NA_DZIS] [int] NOT NULL,
	[DYNAMIKA_ZAKAZEN] [float] NOT NULL,
	[NUMER_KOLEJNY_DNIA] [int] NOT NULL
)
GO

CREATE TABLE [dbo].[CZAS_DIM]
(
	[CZAS_ID] [int] IDENTITY(1,1) NOT NULL,
	[DATA] [date] NOT NULL,
	[DZIEN] [tinyint] NOT NULL,
	[MIESIAC] [tinyint] NOT NULL,
	[ROK] [int] NOT NULL
)
GO

CREATE TABLE [dbo].[GEOGRAFIA_DIM]
(
	[GEOGRAFIA_ID] [int] IDENTITY(1,1) NOT NULL,
	[KONTYNENT] [nvarchar](50) NULL,
	[KRAJ] [nvarchar](50) NULL,
	[POPULACJA] [int] NULL,
	[PKB] [int] NULL
)
GO

CREATE TABLE [dbo].[PACJENT_DIM]
(
	[PACJENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[GEOGRAFIA_ID] [int] NOT NULL,
	[WIEK] [int] NOT NULL,
	[PLEC] [int] NOT NULL
)
GO

CREATE TABLE [dbo].[TYP_ZDARZENIA_DIM]
(
	[TYP_ZDARZENIA_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAZWA_ZDARZENIA] [nvarchar](50) NOT NULL
)
GO

CREATE TABLE [dbo].[ZDARZENIE_PACJENT_DET]
(
	[FAKT_ID] [int] IDENTITY(1,1) NOT NULL,
	[PACJENT_ID] [int] NOT NULL,
	[TYP_ZDARZENIA_ID] [int] NOT NULL,
	[CZAS_ID] [int] NOT NULL
)
GO

-- ****************************************
-- Zaladowanie wymiarow daty i typu zdarzenia
-- ****************************************

INSERT INTO [dbo].[TYP_ZDARZENIA_DIM]
	([NAZWA_ZDARZENIA])
VALUES
	('zakazenie');
INSERT INTO [dbo].[TYP_ZDARZENIA_DIM]
	([NAZWA_ZDARZENIA])
VALUES
	('wyzdrowienie');
INSERT INTO [dbo].[TYP_ZDARZENIA_DIM]
	([NAZWA_ZDARZENIA])
VALUES
	('smierc');
GO

DECLARE @startdate DATE = '2020-01-21'
DECLARE @enddaste DATE = '2021-01-21'

WHILE @startdate < @enddaste
BEGIN
	INSERT INTO [dbo].[CZAS_DIM]
		([DATA], [DZIEN], [MIESIAC], [ROK])
	VALUES(
			@startdate,
			DATEPART(day, @startdate),
			DATEPART(month, @startdate),
			DATEPART(year, @startdate))
	SET @startdate = DATEADD(day, 1, @startdate)
END
GO

-- ****************************************
-- Klucze glowne
-- ****************************************

ALTER TABLE [dbo].[TEMPO_WIRUSA_SUM] 
	ADD CONSTRAINT [PK_TEMPO_WIRUSA] PRIMARY KEY CLUSTERED ([FAKT_ID]);
GO

ALTER TABLE [dbo].[CZAS_DIM] 
	ADD CONSTRAINT [PK_CZAS] PRIMARY KEY CLUSTERED ([CZAS_ID]);
GO

ALTER TABLE [dbo].[GEOGRAFIA_DIM] 
	ADD CONSTRAINT [PK_GEOGRAFIA] PRIMARY KEY CLUSTERED ([GEOGRAFIA_ID]);
GO

ALTER TABLE [dbo].[PACJENT_DIM] 
	ADD CONSTRAINT [PK_PACJENT] PRIMARY KEY CLUSTERED ([PACJENT_ID]);
GO

ALTER TABLE [dbo].[TYP_ZDARZENIA_DIM] 
	ADD CONSTRAINT [PK_TYP_ZDARZENIA] PRIMARY KEY CLUSTERED ([TYP_ZDARZENIA_ID]);
GO

ALTER TABLE [dbo].[ZDARZENIE_PACJENT_DET] 
	ADD CONSTRAINT [PK_STAN_PACJENTA] PRIMARY KEY CLUSTERED ([FAKT_ID]);
GO

-- ****************************************
-- Klucze obce
-- ****************************************

ALTER TABLE [dbo].[TEMPO_WIRUSA_SUM] ADD 
	CONSTRAINT [FK_TEMPO_WIRUSA_CZAS] FOREIGN KEY ([CZAS_ID]) REFERENCES [dbo].[CZAS_DIM] ([CZAS_ID]),
	CONSTRAINT [FK_TEMPO_WIRUSA_GEOGRAFIA] FOREIGN KEY ([GEOGRAFIA_ID]) REFERENCES [dbo].[GEOGRAFIA_DIM] ([GEOGRAFIA_ID]);
GO

ALTER TABLE [dbo].[ZDARZENIE_PACJENT_DET] ADD 
	CONSTRAINT [FK_ZDARZENIE_PACJENT_CZAS] FOREIGN KEY ([CZAS_ID]) REFERENCES [dbo].[CZAS_DIM] ([CZAS_ID]),
	CONSTRAINT [FK_ZDARZENIE_PACJENT_TYP_ZDARZENIA] FOREIGN KEY ([TYP_ZDARZENIA_ID]) REFERENCES [dbo].[TYP_ZDARZENIA_DIM] ([TYP_ZDARZENIA_ID]),
	CONSTRAINT [FK_ZDARZENIE_PACJENT_PACJENT] FOREIGN KEY ([PACJENT_ID]) REFERENCES [dbo].[PACJENT_DIM] ([PACJENT_ID]);
GO

ALTER TABLE [dbo].[PACJENT_DIM] ADD
	CONSTRAINT [FK_PACJENT_GEOGRAFIA] FOREIGN KEY ([GEOGRAFIA_ID]) REFERENCES [dbo].[GEOGRAFIA_DIM] ([GEOGRAFIA_ID]);
GO





