--SELECT CZAS, GEOGRAFIA, MIN(LICZBA_ZAKAZENI_OGOLEM) as lz,
--ROW_NUMBER() OVER (PARTITION BY GEOGRAFIA ORDER BY CZAS) AS nkd
--INTO #processTable
--FROM stage_tempo_fact
--WHERE LICZBA_ZAKAZENI_OGOLEM > 0
--GROUP BY CZAS, GEOGRAFIA

UPDATE sf
SET sf.NUMER_KOLEJNY_DNIA = pt.nkd
FROM
stage_tempo_fact AS sf
INNER JOIN 
(SELECT CZAS, GEOGRAFIA, MIN(LICZBA_ZAKAZENI_OGOLEM) as lz,
ROW_NUMBER() OVER (PARTITION BY GEOGRAFIA ORDER BY CZAS) AS nkd
FROM stage_tempo_fact
WHERE LICZBA_ZAKAZENI_OGOLEM > 0
GROUP BY CZAS, GEOGRAFIA) AS pt
ON sf.CZAS = pt.CZAS AND sf.GEOGRAFIA = pt.GEOGRAFIA

-------------------------------------------------------------------------------------------
SELECT CZAS, GEOGRAFIA, NUMER_KOLEJNY_DNIA, LICZBA_ZAKAZENI_OGOLEM FROM stage_tempo_fact
ORDER BY GEOGRAFIA, CZAS